name: Push to Another Repository

on:
  push:
    branches:
      - main  # Replace with the source branch you want to trigger the workflow
permissions: write-all

jobs:     
  wapiti_scan:
    name: Wapiti DAST Scan
    runs-on: ubuntu-latest
    needs: [analyze]
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Wapiti
        run: |
          sudo apt-get update
          sudo apt-get install -y wapiti
      - name: Run Wapiti scan
        run: |
          wapiti -u http://192.168.0.108:8501  -o wapiti-report.html
      - name: Upload Wapiti HTML report
        uses: actions/upload-artifact@v2
        with:
          name: wapiti-report
          path: wapiti-report.html
